example_data = [{'name': '1. A window with a dropshadow and an image of the twitter failwhale crying in its center',
                 'type': 'GROUP', 'node': {'children': [{'name': 'Window', 'type': 'RECTANGLE',
                                                         'node': {'color': {'r': 1.0, 'g': 1.0, 'b': 1.0}, 'opacity': 1,
                                                                  'position': {'x': 200, 'y': 200}, 'cornerRadius': 0,
                                                                  'width': 400, 'height': 276, 'strokeWeight': 1,
                                                                  'dropShadow': 4}},
                                                        {'name': 'Image prompt: the twitter failwhale crying',
                                                         'type': 'RECTANGLE',
                                                         'node': {'color': {'r': 0.0, 'g': 0.0, 'b': 0.0}, 'opacity': 1,
                                                                  'position': {'x': 304, 'y': 284}, 'cornerRadius': 0,
                                                                  'width': 184, 'height': 104, 'strokeWeight': 1}}]}}]

js_diff = {'node': {'children': {0: {'node': {'children': {1: {'node': {'color': '#ff0000'}}}}}}}}
scene = [{'name': 'Final Output',
          'type': 'GROUP',
          'node': {'children': [{'name': 'Group',
                                 'type': 'GROUP',
                                 'node': {'children': [{'name': 'Rectangle',
                                                        'type': 'RECTANGLE',
                                                        'node': {'color': {'r': 1, 'g': 1, 'b': 1},
                                                                 'opacity': 1,
                                                                 'position': {'x': 200, 'y': 200},
                                                                 'cornerRadius': 0,
                                                                 'width': 400,
                                                                 'height': 236,
                                                                 'strokeWeight': 1}},
                                                       {'name': 'Hello, world!',
                                                        'type': 'TEXT',
                                                        'node': {'characters': 'Hello, world!',
                                                                 'color': {'r': 0, 'g': 0, 'b': 0},
                                                                 'fontSize': 32,
                                                                 'fontWeight': 400,
                                                                 'position': {'x': 200, 'y': 292},
                                                                 'width': 400,
                                                                 'height': 40,
                                                                 'textAlignHorizontal': 'CENTER'}}]}}]}}]
